/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-04-14 19:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"bg\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login or Register Page</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("a:link, a:visited {\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:active {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row::after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("[class*=\"col-\"] {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\tfont-family: \"Lucida Sans\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu ul {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu li {\r\n");
      out.write("\tpadding: 8px 12px;\r\n");
      out.write("\tmargin-bottom: 7px;\r\n");
      out.write("\tmargin-top: 7px;\r\n");
      out.write("\tbackground-color: #33b5e5;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tbox-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu li:hover {\r\n");
      out.write("\tbackground-color: #0099cc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".aside {\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head2 {\r\n");
      out.write("\tcolor: #33b535;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("/* For mobile phones: */\r\n");
      out.write("[class*=\"col-\"] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg {\r\n");
      out.write("\t/* The image used */\r\n");
      out.write("\tbackground-image: url(\"https://i3.wp.com/www.1966mag.com/wp-content/uploads/2015/07/punta-cana-dominican-republic.jpg\");\r\n");
      out.write("\t/* Full height */\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\t/* Center and scale the image nicely */\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media only screen and (min-width: 600px) {\r\n");
      out.write("\t/* For tablets: */\r\n");
      out.write("\t.col-s-1 {\r\n");
      out.write("\t\twidth: 8.33%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-2 {\r\n");
      out.write("\t\twidth: 16.66%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-3 {\r\n");
      out.write("\t\twidth: 25%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-4 {\r\n");
      out.write("\t\twidth: 33.33%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-5 {\r\n");
      out.write("\t\twidth: 41.66%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-6 {\r\n");
      out.write("\t\twidth: 50%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-7 {\r\n");
      out.write("\t\twidth: 58.33%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-8 {\r\n");
      out.write("\t\twidth: 66.66%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-9 {\r\n");
      out.write("\t\twidth: 75%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-10 {\r\n");
      out.write("\t\twidth: 83.33%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-11 {\r\n");
      out.write("\t\twidth: 91.66%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-s-12 {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media only screen and (min-width: 768px) {\r\n");
      out.write("\t/* For desktop: */\r\n");
      out.write("\t.col-1 {\r\n");
      out.write("\t\twidth: 8.33%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-2 {\r\n");
      out.write("\t\twidth: 16.66%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-3 {\r\n");
      out.write("\t\twidth: 25%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-4 {\r\n");
      out.write("\t\twidth: 33.33%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-5 {\r\n");
      out.write("\t\twidth: 41.66%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-6 {\r\n");
      out.write("\t\twidth: 50%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-7 {\r\n");
      out.write("\t\twidth: 58.33%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-8 {\r\n");
      out.write("\t\twidth: 66.66%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-9 {\r\n");
      out.write("\t\twidth: 75%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-10 {\r\n");
      out.write("\t\twidth: 83.33%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-11 {\r\n");
      out.write("\t\twidth: 91.66%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.col-12 {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".LoginBtn {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 18px 35px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tmargin: 2px 2px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Log {\r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tbox-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0\r\n");
      out.write("\t\trgba(0, 0, 0, 0.19);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text], input[type=password] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 12px 20px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text]:focus, input[type=password]:focus {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\tbackground-color: #3399CC;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 18px 24px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\twidth: 21%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("/* Overwrite default styles of hr */\r\n");
      out.write("hr {\r\n");
      out.write("\tborder: 1px solid #f1f1f1;\r\n");
      out.write("\tmargin-bottom: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon {\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tbackground: royalblue;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tmin-width: 30px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 8px;\r\n");
      out.write("\tmargin-top: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-container {\r\n");
      out.write("\tdisplay: -ms-flexbox; /* IE10 */\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("/* Set a style for the submit button */\r\n");
      out.write(".registerbtn {\r\n");
      out.write("\tbackground-color: royalblue;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 16px 20px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\topacity: 0.9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".registerbtn:hover {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cancelbtn {\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tpadding: 10px 18px;\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgcontainer {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 24px 0 12px 0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".avatar {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\twidth: 25%;\r\n");
      out.write("\theight: 25%;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.avatar {\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("\tborder: 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tpadding: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.pass {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tpadding-top: 16px;\r\n");
      out.write("}\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("\tdisplay: none; /* Hidden by default */\r\n");
      out.write("\tposition: fixed; /* Stay in place */\r\n");
      out.write("\tz-index: 1; /* Sit on top */\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 100%; /* Full width */\r\n");
      out.write("\theight: 100%; /* Full height */\r\n");
      out.write("\toverflow: auto; /* Enable scroll if needed */\r\n");
      out.write("\tbackground-color: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */\r\n");
      out.write("\tpadding-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("/* Modal Content/Box */\r\n");
      out.write(".modal-content {\r\n");
      out.write("\tbackground-color: #fefefe;\r\n");
      out.write("\tmargin: 5% auto 15% auto;\r\n");
      out.write("\t/* 5% from the top, 15% from the bottom and centered */\r\n");
      out.write("\tborder: 1px solid #888;\r\n");
      out.write("\twidth: 80%; /* Could be more or less, depending on screen size */\r\n");
      out.write("}\r\n");
      out.write("/* The Close Button (x) */\r\n");
      out.write(".close {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 25px;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover, .close:focus {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("/* Add padding to containers */\r\n");
      out.write(".container {\r\n");
      out.write("\tpadding: 16px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write("/* Add Zoom Animation */\r\n");
      out.write(".animate {\r\n");
      out.write("\t-webkit-animation: animatezoom 0.6s;\r\n");
      out.write("\tanimation: animatezoom 0.6s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("-webkit-keyframes animatezoom {\r\n");
      out.write("\tfrom {-webkit-transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\t-webkit-transform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes animatezoom {\r\n");
      out.write("\tfrom {transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\ttransform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("/* Change styles for span and cancel button on extra small screens */\r\n");
      out.write("@media screen and (max-width: 300px) {\r\n");
      out.write("\tspan.pass {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cancelbtn {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tex {\r\n");
      out.write("\t\tfont-size: 18px;\r\n");
      out.write("\t\tfon: bold;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"head2\">\r\n");
      out.write("\t\t<div class=\"aside\">\r\n");
      out.write("\t\t\t<h1 style=\"color: PapayaWhip;\" align=center>Login or Register to\r\n");
      out.write("\t\t\t\tStart Bidding!</h1>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('id01').style.display='block'\"\r\n");
      out.write("\t\t\t\t\tclass=\"LoginBtn Log\">Login</button>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"id01\" class=\"modal\">\r\n");
      out.write("\t\t\t\t<form method=\"POST\" class=\"modal-content animate\" action=\"login.jsp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"imgcontainer\">\r\n");
      out.write("\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"document.getElementById('id01').style.display='none'\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"close\" title=\"Close Modal\">&times;</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<h2 style=\"color: royalblue\";>\r\n");
      out.write("\t\t\t\t\t\t\t<center><strong>Login</strong></center>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"user\" style=\"color: black;\" align=\"left\"><b>Username/Email</b></label><br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-user-circle-o icon\"></i> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Username/Email\" name=\"username\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"pass\" style=\"color: black;\" align=\"left\"><b>Password</b></label><br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-key icon\"></i> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Password\" name=\"pass\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"registerbtn\">Login</button>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"Remember Me\" style=\"color: black;\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"checkbox\" checked=\"checked\" name=\"remember\">\r\n");
      out.write("\t\t\t\t\t\t\tRemember me\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"container\" style=\"background-color: #f1f1f1\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"document.getElementById('id01').style.display='none'\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"cancelbtn\">Cancel</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('id02').style.display='block'\"\r\n");
      out.write("\t\t\t\t\tclass=\"LoginBtn Log\">Register</button>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t<div id=\"id02\" class=\"modal\">\r\n");
      out.write("\t\t\t\t<form method=\"POST\" class=\"modal-content animate\"\r\n");
      out.write("\t\t\t\t\taction=\"userReg.jsp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tex\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Please fill in this form to create an account.</strong>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"email\" style=\"color: black;\"><b>Email/UserName</b></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-user-circle-o icon\"></i> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter Email\" name=\"email_usr\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"psw\" style=\"color: black;\"><b>Password</b></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-key icon\"></i> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter Password\" name=\"psw\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"registerbtn\">Register</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\" style=\"background-color: #f1f1f1\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"document.getElementById('id02').style.display='none'\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"cancelbtn\">Cancel</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<!--<h3 style=\"color:RoyalBlue  ;\" align=center>Login or SignUp!</h3>-->\r\n");
      out.write("\t\t\t<p align=center>Copyright ©2019</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("// Get the modal\r\n");
      out.write("var modal = document.getElementById('id01');\r\n");
      out.write("var modal = document.getElementById('id02');\r\n");
      out.write("// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("window.onclick = function(event) {\r\n");
      out.write("    if (event.target == modal) {\r\n");
      out.write("        modal.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
